package com.publiccms.entities.cms;

// Generated 2016-3-4 22:54:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sanluan.common.source.entity.MyColumn;

/**
 * CmsPageDataAttribute generated by hbm2java
 */
@Entity
@Table(name = "cms_page_data_attribute")
public class CmsPageDataAttribute implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "分类")
    private int pageDataId;
    @MyColumn(title = "扩展数据")
    private String data;

    public CmsPageDataAttribute() {
    }

    public CmsPageDataAttribute(int pageDataId) {
        this.pageDataId = pageDataId;
    }

    public CmsPageDataAttribute(int pageDataId, String data) {
        this.pageDataId = pageDataId;
        this.data = data;
    }

    @Id
    @Column(name = "page_data_id", unique = true, nullable = false)
    public int getPageDataId() {
        return this.pageDataId;
    }

    public void setPageDataId(int pageDataId) {
        this.pageDataId = pageDataId;
    }

    @Column(name = "data")
    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
