package com.publiccms.entities.sys;
// Generated 2016-12-6 20:53:58 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.sanluan.common.source.entity.MyColumn;

/**
 * SysConfigDataId generated by hbm2java
 */
@Embeddable
public class SysConfigDataId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @MyColumn(title = "站点", condition = true)
    @JsonIgnore
    private int siteId;
    @MyColumn(title = "编码", condition = true)
    private String code;
    @MyColumn(title = "子编码", condition = true)
    private String itemCode;

    public SysConfigDataId() {
    }

    public SysConfigDataId(int siteId, String code, String itemCode) {
        this.siteId = siteId;
        this.code = code;
        this.itemCode = itemCode;
    }

    @Column(name = "site_id", nullable = false)
    public int getSiteId() {
        return this.siteId;
    }

    public void setSiteId(int siteId) {
        this.siteId = siteId;
    }

    @Column(name = "code", nullable = false, length = 50)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "item_code", nullable = false, length = 50)
    public String getItemCode() {
        return this.itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof SysConfigDataId))
            return false;
        SysConfigDataId castOther = (SysConfigDataId) other;

        return (this.getSiteId() == castOther.getSiteId())
                && ((this.getCode() == castOther.getCode())
                        || (this.getCode() != null && castOther.getCode() != null && this.getCode().equals(castOther.getCode())))
                && ((this.getItemCode() == castOther.getItemCode()) || (this.getItemCode() != null
                        && castOther.getItemCode() != null && this.getItemCode().equals(castOther.getItemCode())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSiteId();
        result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
        result = 37 * result + (getItemCode() == null ? 0 : this.getItemCode().hashCode());
        return result;
    }

}
